ekraujins_key: &ekraujins
  - age1vl3rrem8cy4zcszckvt2td6d39qn6n530ta6kfqzs4v7hklvuyms2zxlnf


creation_rules:
  - path_regex: secrets.yaml
    key_groups:
      - age: *ekraujins
  - path_regex: ./secrets.yaml
    key_groups:
      - age: *ekraujins
